#! /bin/bash

# watch the battery, and if it gets too low, flash the backlight.

test $UID -eq 0 || {
  echo 'must be run as root in order to control lights' 1>&2
  exit 1
}

set -e

is_charging () {
  acpi -b | grep Charging > /dev/null
}

battery_level () {
  #parse acpi output
  x=$(acpi -b)
  x=${x#*, }
  x=${x%\%*};
  echo $x
}

# this is the backlight on my archbookair,
# your computer may have something similar.
KBBLIGHT='/sys/class/leds/smc::kbd_backlight'

check () {
  is_charging || test "$(battery_level)" -gt 10
}

while true; do

  # poll battery level every 10 seconds
  # if the level is too low, go into warn loop
  # flash the backlight until someone plugs in the backlight.
  # or the computer has more battery (maybe someone plugged it in while turned off)

  until check; do
    echo 100 > $KBBLIGHT/brightness
    sleep 0.5
    echo 0 > $KBBLIGHT/brightness
    sleep 0.5
  done

  sleep 10

done

